export const IPC = {
  CHAT_SEND: 'chat:send',
  CHAT_STOP: 'chat:stop',
  CHAT_NEW: 'chat:new',
  CHAT_LIST: 'chat:list',
  CHAT_LOAD: 'chat:load',
  CHAT_DELETE: 'chat:delete',
  BROWSER_NAVIGATE: 'browser:navigate',
  BROWSER_BACK: 'browser:back',
  BROWSER_FORWARD: 'browser:forward',
  BROWSER_REFRESH: 'browser:refresh',
  BROWSER_SET_BOUNDS: 'browser:set-bounds',
  BROWSER_TAB_NEW: 'browser:tab:new',
  BROWSER_TAB_LIST: 'browser:tab:list',
  BROWSER_TAB_SWITCH: 'browser:tab:switch',
  BROWSER_TAB_CLOSE: 'browser:tab:close',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  API_KEY_GET: 'api-key:get',
  API_KEY_SET: 'api-key:set',
  MODEL_GET: 'model:get',
  MODEL_SET: 'model:set',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
} as const;

export const IPC_EVENTS = {
  CHAT_STREAM_TEXT: 'chat:stream:text',
  CHAT_STREAM_END: 'chat:stream:end',
  CHAT_THINKING: 'chat:thinking',
  CHAT_TOOL_ACTIVITY: 'chat:tool-activity',
  BROWSER_URL_CHANGED: 'browser:url-changed',
  BROWSER_TITLE_CHANGED: 'browser:title-changed',
  BROWSER_LOADING: 'browser:loading',
} as const;
