export const IPC = {
  CHAT_SEND: 'chat:send',
  CHAT_STOP: 'chat:stop',
  CHAT_PAUSE: 'chat:pause',
  CHAT_RESUME: 'chat:resume',
  CHAT_ADD_CONTEXT: 'chat:add-context',
  CHAT_RATE_TOOL: 'chat:rate-tool',
  CHAT_NEW: 'chat:new',
  CHAT_LIST: 'chat:list',
  CHAT_LOAD: 'chat:load',
  CHAT_DELETE: 'chat:delete',
  BROWSER_NAVIGATE: 'browser:navigate',
  BROWSER_BACK: 'browser:back',
  BROWSER_FORWARD: 'browser:forward',
  BROWSER_REFRESH: 'browser:refresh',
  BROWSER_SET_BOUNDS: 'browser:set-bounds',
  BROWSER_TAB_NEW: 'browser:tab:new',
  BROWSER_TAB_LIST: 'browser:tab:list',
  BROWSER_TAB_SWITCH: 'browser:tab:switch',
  BROWSER_TAB_CLOSE: 'browser:tab:close',
  BROWSER_HISTORY_MATCH: 'browser:history-match',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  API_KEY_GET: 'api-key:get',
  API_KEY_SET: 'api-key:set',
  MODEL_GET: 'model:get',
  MODEL_SET: 'model:set',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  // Process management
  PROCESS_LIST: 'process:list',
  PROCESS_DETACH: 'process:detach',
  PROCESS_ATTACH: 'process:attach',
  PROCESS_CANCEL: 'process:cancel',
  PROCESS_DISMISS: 'process:dismiss',
  RUN_LIST: 'run:list',
  RUN_GET: 'run:get',
  RUN_EVENTS: 'run:events',
  RUN_CHANGES: 'run:changes',
  RUN_APPROVALS: 'run:approvals',
  RUN_APPROVE: 'run:approve',
  RUN_DENY: 'run:deny',
} as const;

export const IPC_EVENTS = {
  CHAT_STREAM_TEXT: 'chat:stream:text',
  CHAT_STREAM_END: 'chat:stream:end',
  CHAT_THINKING: 'chat:thinking',
  CHAT_TOOL_ACTIVITY: 'chat:tool-activity',
  CHAT_TOOL_STREAM: 'chat:tool-stream',
  BROWSER_URL_CHANGED: 'browser:url-changed',
  BROWSER_TITLE_CHANGED: 'browser:title-changed',
  BROWSER_LOADING: 'browser:loading',
  BROWSER_TABS_CHANGED: 'browser:tabs-changed',
  // Process events (pushed from main to renderer)
  PROCESS_LIST_CHANGED: 'process:list',
} as const;
